rules:
  - find: '#/\*\*\s*\n\s*\*\s*@Route\((.*?)\)\s*\n\s*\*/#s'
    replace: "#[Route(modifthis)]"
  # Pour @ORM\Entity et d'autres annotations ORM similaires
  - find: '#@\ORM\\([A-Za-z]+)\((.*?)\)#s'
    replace: "#[ORM\\\(modifthis)]"
  # Pour @UniqueEntity
  - find: '#@\UniqueEntity\((.*?)\)#s'
    replace: "#[UniqueEntity(modifthis)]"
parameters:
  - for: '='
    put: ': '
  - for: '{'
    put: '['
  - for: '}'
    put: ']'
  - for: '\[id\]'
    put: '{id}'
    # Ajoutez d'autres règles de remplacement au besoin
